apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: jrno/k8s-sample-db:3
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin # TODO: from secrets
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password # TODO: from secrets
        - name: MONGO_INITDB_DATABASE
          value: sampleStackDB # TODO: from secrets
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc