kind: Deployment
apiVersion: apps/v1
metadata:
    name: proxy
    labels:
      app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: jrno/k8s-sample-proxy
        imagePullPolicy: Never # prevent registry lookup
        ports:
          - containerPort: 80
          - containerPort: 443