apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  type: ClusterIP # also default
  selector:
    app: server
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000