apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: server
  name: server-env
data:
   NODE_ENV: "production"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: jrno/k8s-sample-server:3
        imagePullPolicy: Never # prevent registry lookup
        ports:
          - containerPort: 3000
        envFrom:
          - configMapRef:
              name: server-env