kind: Service
apiVersion: v1
metadata:
    name: nodeport-blue
    labels:
      app: nodeport-blue
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: sample-app
    role: blue