services:
  db:
    image: jrno/k8s-sample-db:3
    build: ./db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=sampleStackDB
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  proxy:
    image: jrno/k8s-sample-proxy:3
    build: ./proxy

  worker:
    image: jrno/k8s-sample-worker:3
    build: ./worker
    environment:
      - MONGO_URI=mongodb://admin:password@db:27017
      - MONGO_DB_NAME=sampleStackDB
      - MEASUREMENT_INTERVAL_SECONDS=1

  server:
    image: jrno/k8s-sample-server:3
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app